name: wormhole
version: 1.0.0
description: none
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  dart_model:
    git:
      url: https://github.com/DerWolf01/dart_model.git
      ref: main
  analyzer: ^6.4.0
  build_runner: ^2.0.0
  characters: ^1.3.0
  reflectable: any
dev_dependencies:
  build_test: ^2.2.0
  lints: ^3.0.0
  test: ^1.25.0